name: Actualización de Cliente Recurrente

on:
  issues:
    types:
      - closed
    labels:
      - actualizar-cliente

jobs:
  notificar-actualizacion:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Cliente actualizado ✅",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Cliente actualizado ✅\n*Issue:* <${{ github.event.issue.html_url }}|#${{ github.event.issue.number }}>\n*Título:* ${{ github.event.issue.title }}\n*Descripción:* ${{ github.event.issue.body }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
