name: Modificación del Código

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  notificar-modificacion:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar notificación a Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Modificación del código detectada 🛠️",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Modificación del código detectada 🛠️\n*Rama:* ${{ github.ref }}\n*Commit:* <${{ github.event.head_commit.url }}|${{ github.event.head_commit.id }}>\n*Mensaje:* ${{ github.event.head_commit.message }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
